### ISSUE TITLE
Setup Recipe App Kanban board

### ISSUE THREAD

**Issue by vangelif** [vangelif/recipe_app#14]
# In this Project we are a total of 2 members
## Member One:
@HenaryKhuraijam 
## Member Two:
@vangelif 

## Link:
https://github.com/users/vangelif/projects/3/views/1

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @vangelif and @HenaryKhuraijam,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Provide the link your kanban not your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼, 

![approved](https://github.com/vangelif/recipe_app/assets/64643995/a5345f2f-5e53-496c-a5fd-78044cb9cba5)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Every requirement for the project has been captured in the Kanban board👍🏼.
- [x] Points are fairly distributed amongst team members👍🏼.
- [x] Each card has a description👍🏼.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
